version: "3.3"

services:
    backend:
        restart: always
        build:
            context: ./app
            dockerfile: Dockerfile
        working_dir: /app
        command: /bin/bash -c "uvicorn main:app --reload --host 0.0.0.0"
        env_file:
            - ./.dev.env
        volumes:
            - ./app/:/app/:delegated
        expose:
            - 8000
        ports:
            - 8000:8000
        depends_on:
            - postgres

    postgres:
        image: postgres:11.5-alpine
        volumes:
            - "postgres:/var/lib/postgresql/data"
        expose:
            - 5432
        env_file:
            - ./.dev.env
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U 'postgres' -d postgres",
                ]
            timeout: 10s
            interval: 20s
            retries: 3

volumes:
    postgres:
